/* Auto-generated from auth\forgot_password.html */
import React from "react";

export const rawHtml = "{% extends \"base.html\" %}\r\n\r\n{% block title %}Şifremi Unuttum - Arsa Analiz Platformu{% endblock %}\r\n\r\n{% block main_class %}w-full{% endblock %}\r\n\r\n{% block content %}\r\n<div class=\"min-h-screen bg-gradient-to-br from-primary-600 to-purple-700 flex items-center justify-center p-4\">\r\n    <div class=\"w-full max-w-md\">\r\n        <div class=\"bg-white rounded-xl shadow-large p-8\">\r\n            <div class=\"text-center mb-6\">\r\n                <i class=\"fas fa-key text-5xl text-primary-600 mb-4\"></i>\r\n                <h3 class=\"text-2xl font-bold text-gray-900\">Şifremi Unuttum</h3>\r\n                <p class=\"text-gray-600 mt-2\">E-posta adresinizi girin, size şifre sıfırlama bağlantısı gönderelim</p>\r\n            </div>\r\n            <form action=\"{{ url_for('auth.forgot_password') }}\" method=\"post\" id=\"forgotPasswordForm\" class=\"space-y-4\">\r\n                <div>\r\n                    <label for=\"email\" class=\"block text-sm font-medium text-gray-700 mb-2\">\r\n                        <i class=\"fas fa-envelope mr-2\"></i>E-Posta\r\n                    </label>\r\n                    <input type=\"email\" class=\"form-control w-full\" id=\"email\" name=\"email\" placeholder=\"E-posta adresiniz\" required>\r\n                    <div class=\"text-red-600 text-sm mt-1 hidden\">Lütfen geçerli bir e-posta adresi giriniz.</div>\r\n                </div>\r\n                <div>\r\n                    <button type=\"submit\" class=\"btn-primary w-full py-3 text-lg\">\r\n                        <i class=\"fas fa-paper-plane mr-2\"></i>Şifre Sıfırlama Bağlantısı Gönder\r\n                    </button>\r\n                </div>\r\n            </form>\r\n\r\n            <div class=\"mt-6 text-center\">\r\n                <a href=\"{{ url_for('auth.login') }}\" class=\"text-primary-600 hover:text-primary-700 transition-colors\">\r\n                    <i class=\"fas fa-arrow-left mr-1\"></i>Giriş sayfasına dön\r\n                </a>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n{% endblock %}\r\n\r\n{% block extra_js %}\r\n<script>\r\n    // Form doğrulama\r\n    document.getElementById('forgotPasswordForm').addEventListener('submit', function(e) {\r\n        const email = document.getElementById('email');\r\n        const emailRegex = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/;\r\n\r\n        if (!emailRegex.test(email.value)) {\r\n            email.classList.add('border-red-500');\r\n            e.preventDefault();\r\n        } else {\r\n            email.classList.remove('border-red-500');\r\n        }\r\n    });\r\n</script>\r\n{% endblock %}";

export default function AuthForgotPassword(props: { html?: string; wrapperClassName?: string }) {
  const { html = rawHtml, wrapperClassName } = props;
  return (
    <div className={wrapperClassName} dangerouslySetInnerHTML={{ __html: html }} />
  );
}
