"""Add office_id to crm_contacts

Revision ID: bca257d8b960
Revises: 5ea8552e7f56
Create Date: 2025-05-19 01:22:58.321443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'bca257d8b960'
down_revision = '5ea8552e7f56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crm_reminders')
    op.drop_table('portfolio_tag_associations')
    op.drop_table('portfolio_performance')
    op.drop_table('portfolio_groups')
    op.drop_table('portfolio_tags')
    op.drop_table('customer_interactions')
    op.drop_table('customers')
    op.drop_table('crm_settings')
    op.drop_table('appointments')
    op.drop_constraint('FK__analiz_me__anali__395884C4', 'analiz_medya', type_='foreignkey')
    op.create_foreign_key(None, 'analiz_medya', 'arsa_analizleri', ['analiz_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_arsa_analizleri_created_at', table_name='arsa_analizleri')
    op.drop_index('ix_arsa_analizleri_fiyat', table_name='arsa_analizleri')
    op.drop_index('ix_arsa_analizleri_il_ilce', table_name='arsa_analizleri')
    op.drop_index('ix_arsa_analizleri_metrekare', table_name='arsa_analizleri')
    op.drop_index('ix_arsa_analizleri_user_id', table_name='arsa_analizleri')
    op.alter_column('bolge_dagilimi', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bolge_dagilimi', 'il',
               existing_type=sa.VARCHAR(length=50, collation='Turkish_CI_AS'),
               nullable=True)
    op.drop_index('ix_crm_companies_name', table_name='crm_companies')
    op.drop_index('ix_crm_companies_user_id', table_name='crm_companies')
    op.drop_index('IX_crm_contacts_office_id', table_name='crm_contacts')
    op.drop_index('ix_crm_contacts_created_at', table_name='crm_contacts')
    op.drop_index('ix_crm_contacts_status', table_name='crm_contacts')
    op.drop_index('ix_crm_contacts_user_id', table_name='crm_contacts')
    op.drop_constraint('FK_crm_contacts_offices', 'crm_contacts', type_='foreignkey')
    op.create_foreign_key(None, 'crm_contacts', 'offices', ['office_id'], ['id'])
    op.drop_column('crm_contacts', 'last_contact_date')
    op.drop_index('IX_crm_deals_office_id', table_name='crm_deals')
    op.drop_index('ix_crm_deals_company_id', table_name='crm_deals')
    op.drop_index('ix_crm_deals_contact_id', table_name='crm_deals')
    op.drop_index('ix_crm_deals_expected_close_date', table_name='crm_deals')
    op.drop_index('ix_crm_deals_stage', table_name='crm_deals')
    op.drop_index('ix_crm_deals_user_id', table_name='crm_deals')
    op.drop_constraint('FK_crm_deals_offices', 'crm_deals', type_='foreignkey')
    op.create_foreign_key(None, 'crm_deals', 'offices', ['office_id'], ['id'])
    op.alter_column('crm_tasks', 'recurrence_type',
               existing_type=sa.NVARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('crm_tasks', 'recurrence_end_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('crm_tasks', 'task_type',
               existing_type=sa.NVARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("('personal')"))
    op.drop_index('IX_crm_tasks_office_id', table_name='crm_tasks')
    op.drop_index('ix_crm_tasks_due_date', table_name='crm_tasks')
    op.drop_index('ix_crm_tasks_priority', table_name='crm_tasks')
    op.drop_index('ix_crm_tasks_status', table_name='crm_tasks')
    op.drop_index('ix_crm_tasks_user_id', table_name='crm_tasks')
    op.drop_constraint('FK_task_parent', 'crm_tasks', type_='foreignkey')
    op.drop_column('crm_tasks', 'reminder_sent')
    op.drop_column('crm_tasks', 'parent_task_id')
    op.drop_index('ix_portfolio_arsalar_arsa_id', table_name='portfolio_arsalar')
    op.drop_index('ix_portfolio_arsalar_portfolio_id', table_name='portfolio_arsalar')
    op.drop_index('ix_portfolios_created_at', table_name='portfolios')
    op.drop_index('ix_portfolios_user_id', table_name='portfolios')
    op.alter_column('users', 'role',
               existing_type=sa.NVARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("('danışman')"))
    op.drop_constraint('FK_User_ReportsTo', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'offices', ['office_id'], ['id'])
    op.drop_column('users', 'manager_id')
    op.drop_column('users', 'report_to_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('report_to_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('manager_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('FK_User_ReportsTo', 'users', 'users', ['report_to_id'], ['id'])
    op.alter_column('users', 'role',
               existing_type=sa.NVARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("('danışman')"))
    op.create_index('ix_portfolios_user_id', 'portfolios', ['user_id'], unique=False)
    op.create_index('ix_portfolios_created_at', 'portfolios', ['created_at'], unique=False)
    op.create_index('ix_portfolio_arsalar_portfolio_id', 'portfolio_arsalar', ['portfolio_id'], unique=False)
    op.create_index('ix_portfolio_arsalar_arsa_id', 'portfolio_arsalar', ['arsa_id'], unique=False)
    op.add_column('crm_tasks', sa.Column('parent_task_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('crm_tasks', sa.Column('reminder_sent', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=True))
    op.create_foreign_key('FK_task_parent', 'crm_tasks', 'crm_tasks', ['parent_task_id'], ['id'])
    op.create_index('ix_crm_tasks_user_id', 'crm_tasks', ['user_id'], unique=False)
    op.create_index('ix_crm_tasks_status', 'crm_tasks', ['status'], unique=False)
    op.create_index('ix_crm_tasks_priority', 'crm_tasks', ['priority'], unique=False)
    op.create_index('ix_crm_tasks_due_date', 'crm_tasks', ['due_date'], unique=False)
    op.create_index('IX_crm_tasks_office_id', 'crm_tasks', ['office_id'], unique=False)
    op.alter_column('crm_tasks', 'task_type',
               existing_type=sa.String(length=50),
               type_=sa.NVARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("('personal')"))
    op.alter_column('crm_tasks', 'recurrence_end_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)
    op.alter_column('crm_tasks', 'recurrence_type',
               existing_type=sa.String(length=20),
               type_=sa.NVARCHAR(length=50),
               existing_nullable=True)
    op.drop_constraint(None, 'crm_deals', type_='foreignkey')
    op.create_foreign_key('FK_crm_deals_offices', 'crm_deals', 'offices', ['office_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_crm_deals_user_id', 'crm_deals', ['user_id'], unique=False)
    op.create_index('ix_crm_deals_stage', 'crm_deals', ['stage'], unique=False)
    op.create_index('ix_crm_deals_expected_close_date', 'crm_deals', ['expected_close_date'], unique=False)
    op.create_index('ix_crm_deals_contact_id', 'crm_deals', ['contact_id'], unique=False)
    op.create_index('ix_crm_deals_company_id', 'crm_deals', ['company_id'], unique=False)
    op.create_index('IX_crm_deals_office_id', 'crm_deals', ['office_id'], unique=False)
    op.add_column('crm_contacts', sa.Column('last_contact_date', sa.DATETIME(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'crm_contacts', type_='foreignkey')
    op.create_foreign_key('FK_crm_contacts_offices', 'crm_contacts', 'offices', ['office_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_crm_contacts_user_id', 'crm_contacts', ['user_id'], unique=False)
    op.create_index('ix_crm_contacts_status', 'crm_contacts', ['status'], unique=False)
    op.create_index('ix_crm_contacts_created_at', 'crm_contacts', ['created_at'], unique=False)
    op.create_index('IX_crm_contacts_office_id', 'crm_contacts', ['office_id'], unique=False)
    op.create_index('ix_crm_companies_user_id', 'crm_companies', ['user_id'], unique=False)
    op.create_index('ix_crm_companies_name', 'crm_companies', ['name'], unique=False)
    op.alter_column('bolge_dagilimi', 'il',
               existing_type=sa.VARCHAR(length=50, collation='Turkish_CI_AS'),
               nullable=False)
    op.alter_column('bolge_dagilimi', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('ix_arsa_analizleri_user_id', 'arsa_analizleri', ['user_id'], unique=False)
    op.create_index('ix_arsa_analizleri_metrekare', 'arsa_analizleri', ['metrekare'], unique=False)
    op.create_index('ix_arsa_analizleri_il_ilce', 'arsa_analizleri', ['il', 'ilce'], unique=False)
    op.create_index('ix_arsa_analizleri_fiyat', 'arsa_analizleri', ['fiyat'], unique=False)
    op.create_index('ix_arsa_analizleri_created_at', 'arsa_analizleri', ['created_at'], unique=False)
    op.drop_constraint(None, 'analiz_medya', type_='foreignkey')
    op.create_foreign_key('FK__analiz_me__anali__395884C4', 'analiz_medya', 'arsa_analizleri', ['analiz_id'], ['id'])
    op.create_table('appointments',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=200, collation='Turkish_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(collation='Turkish_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('start_time', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('end_time', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=200, collation='Turkish_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20, collation='Turkish_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('reminder', mssql.BIT(), autoincrement=False, nullable=True),
    sa.Column('reminder_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='FK__appointme__custo__5F7E2DAC'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='FK__appointme__user___5E8A0973'),
    sa.PrimaryKeyConstraint('id', name='PK__appointm__3213E83F36F9B7F7')
    )
    op.create_table('crm_settings',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('default_currency', sa.VARCHAR(length=10, collation='Turkish_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('date_format', sa.VARCHAR(length=20, collation='Turkish_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('time_format', sa.VARCHAR(length=20, collation='Turkish_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('contact_statuses', sa.VARCHAR(collation='Turkish_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('deal_stages', sa.VARCHAR(collation='Turkish_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('task_statuses', sa.VARCHAR(collation='Turkish_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('task_priorities', sa.VARCHAR(collation='Turkish_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('email_notifications', mssql.BIT(), autoincrement=False, nullable=True),
    sa.Column('notification_types', sa.VARCHAR(collation='Turkish_CI_AS'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='FK__crm_setti__user___3DE82FB7'),
    sa.PrimaryKeyConstraint('id', name='PK__crm_sett__3213E83FDA0B3D55')
    )
    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100, collation='Turkish_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120, collation='Turkish_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20, collation='Turkish_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('company', sa.VARCHAR(length=100, collation='Turkish_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=100, collation='Turkish_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(collation='Turkish_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('customer_type', sa.VARCHAR(length=20, collation='Turkish_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(collation='Turkish_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20, collation='Turkish_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='FK__customers__user___57DD0BE4', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='PK__customer__3213E83F048B121B')
    )
    op.create_table('customer_interactions',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('interaction_type', sa.VARCHAR(length=50, collation='Turkish_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(collation='Turkish_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('outcome', sa.VARCHAR(length=50, collation='Turkish_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('next_action', sa.VARCHAR(length=200, collation='Turkish_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('next_action_date', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='FK__customer___creat__634EBE90'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='FK__customer___custo__625A9A57'),
    sa.PrimaryKeyConstraint('id', name='PK__customer__3213E83FFA402A41')
    )
    op.create_table('portfolio_tags',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50, collation='Turkish_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(length=7, collation='Turkish_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='FK__portfolio__user___4F47C5E3'),
    sa.PrimaryKeyConstraint('id', name='PK__portfoli__3213E83FD5B2E583')
    )
    op.create_table('portfolio_groups',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100, collation='Turkish_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(collation='Turkish_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='FK__portfolio__user___5224328E'),
    sa.PrimaryKeyConstraint('id', name='PK__portfoli__3213E83FB6F2DB2F')
    )
    op.create_table('portfolio_performance',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_value', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('value_change', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('change_percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('risk_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('measurement_date', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name='FK__portfolio__portf__55009F39'),
    sa.PrimaryKeyConstraint('id', name='PK__portfoli__3213E83FDC9CBCB9')
    )
    op.create_table('portfolio_tag_associations',
    sa.Column('portfolio_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name='FK__portfolio__portf__5AB9788F'),
    sa.ForeignKeyConstraint(['tag_id'], ['portfolio_tags.id'], name='FK__portfolio__tag_i__5BAD9CC8'),
    sa.PrimaryKeyConstraint('portfolio_id', 'tag_id', name='PK__portfoli__36C738448E27C21C')
    )
    op.create_table('crm_reminders',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deal_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=200, collation='Turkish_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(collation='Turkish_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('reminder_time', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('is_sent', mssql.BIT(), autoincrement=False, nullable=True),
    sa.Column('sent_at', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('notification_type', sa.VARCHAR(length=20, collation='Turkish_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], name='FK__crm_remin__conta__2057CCD0'),
    sa.ForeignKeyConstraint(['deal_id'], ['crm_deals.id'], name='FK__crm_remin__deal___214BF109'),
    sa.ForeignKeyConstraint(['task_id'], ['crm_tasks.id'], name='FK__crm_remin__task___22401542'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='FK__crm_remin__user___1F63A897'),
    sa.PrimaryKeyConstraint('id', name='PK__crm_remi__3213E83F04C28496')
    )
    # ### end Alembic commands ###
